version: "3"
services:
    proxy:
        image: jc21/nginx-proxy-manager:latest
        container_name: proxy-manager
        environment:
            DISABLE_IPV6: 'true'
        volumes:
            - ./docker-data/nginx-proxy-manager:/data
            - ./letsencrypt:/etc/letsencrypt
        restart: unless-stopped
        network_mode: "host"

    portainer:
        image: portainer/portainer-ce:latest
        container_name: portainer
        ports:
            - 9443:9443
        command: --admin-password '$$2y$$05$$GIREErZJylvl7EnNeBO8nu9FgR5aDsa4oG5kNpSGPMNkW.GG6/9TS' #password
        volumes:
            - ./docker-data/portainer:/data
            - /var/run/docker.sock:/var/run/docker.sock
        restart: unless-stopped
        networks:
            - local

    mariadb:
        image: mariadb:10.11
        container_name: mariadb
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: 'password'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: 'laravel'
            MYSQL_USER: 'laravel'
            MYSQL_PASSWORD: 'password'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - ./docker-data/mariadb:/var/lib/mysql
        command: --max_allowed_packet=1073741824 # 1GB
        #docker exec -i mariadb sh -c 'exec mariadb -uroot -ppassword --max-allowed-packet=1073741824 --database bd_destino' < /home/.../dump.sql
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-ppassword"]
            retries: 3
            timeout: 5s
        networks:
            - local
        restart: unless-stopped

    redis:
        image: redis:alpine
        container_name: redis
        ports:
            - 6379:6379
        volumes:
            - ./docker-data/redis:/data
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
            retries: 3
            timeout: 5s
        networks:
            - local
        restart: on-failure

    soketi:
        image: quay.io/soketi/soketi:latest-16-alpine
        container_name: soketi
        environment:
            SOKETI_DEBUG: 1
            SOKETI_METRICS_SERVER_PORT: 9601
            DEFAULT_APP_ID: 'app-id'
            DEFAULT_APP_KEY: 'app-key'
            DEFAULT_APP_SECRET: 'app-secret'
        ports:
            - 6001:6001
            - 9601:9601
        networks:
            - local
        restart: on-failure

    meilisearch:
        image: getmeili/meilisearch:latest
        container_name: meilisearch
        ports:
            - 7700:7700
        volumes:
            - ./docker-data/meilisearch:/meili_data
        healthcheck:
            test: ["CMD", "wget", "--no-verbose", "--spider",  "http://localhost:7700/health"]
            retries: 3
            timeout: 5s
        networks:
            - local
        restart: on-failure

    mailpit:
        image: axllent/mailpit:latest
        container_name: mailpit
        ports:
            - 1025:1025
            - 8025:8025
        networks:
            - local
        restart: on-failure

    minio:
        image: minio/minio:latest
        container_name: minio
        ports:
            - 9000:9000
            - 8900:8900
        environment:
            MINIO_ROOT_USER: 'admin'
            MINIO_ROOT_PASSWORD: 'password'
        volumes:
            - ./docker-data/minio:/data/minio
        command: minio server /data/minio --console-address ":8900"
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
            retries: 3
            timeout: 5s
        networks:
            - local
        restart: on-failure
networks:
    local:
        driver: bridge
