global:
    sendAnonymousUsage: false

api:
    dashboard: true
    insecure: true

serversTransport:
    insecureSkipVerify: true

providers:
    docker:
        endpoint: "unix:///var/run/docker.sock"
        watch: true
        exposedByDefault: true
        network: proxy

    file:
        filename: /etc/traefik/dynamic.yml
        watch: true

log:
    level: DEBUG
    format: common

entryPoints:
    http:
        address: ":80"
        http:
          redirections:
            entryPoint:
              to: https
              scheme: https
    https:
        address: ":443"
